<?php

/**
 * @file
 * Main file for creating the responsive images.
 */

define('RESPONSIVE_IMAGE_STYLES_STEPS', 160);

/**
 * Implements hook_theme().
 */
function responsive_image_styles_theme() {
  return array(
    'responsive_image' => array(
      'variables' => array(
        'style' => NULL,
        'file' => array(),
        'attributes' => array(),
        'data_options' => array(),
      ),
      'file' => 'responsive_image_styles.theme.inc',
    ),
    'responsive_image_styles_scale_min_summary' => array(
      'variables' => array('data' => NULL),
    ),
  );
}

/**
 * Implements hook_page_build().
 *
 * Add css to the backend to fixing padding or margin on focalpoint images.
 */
function responsive_image_styles_page_build(&$page) {
  if (path_is_admin(current_path())) {
    ctools_add_css('responsive_image_styles_backend', 'responsive_image_styles');
  }
}

/**
 * Implementation of hool_tcm_fixture_functions_alter().
 */
function responsive_image_styles_tcm_fixture_functions_alter(&$functions) {
  $functions['responsive_image'] = 'responsive_image_styles_fixture_function';
}

/**
 * Fixture function for a responsive-image.
 */
function responsive_image_styles_fixture_function($mode = 'adpative') {
  $ext = '_' . rand(1, 3) . '.jpg';
  $file_uri = 'public://responsive_image_example' . $ext;
  if (!file_exists($file_uri)) {
    $source = drupal_get_path('module', 'responsive_image_styles') . '/example' . $ext;
    file_unmanaged_copy($source, $file_uri, FILE_EXISTS_REPLACE);
  }
  $file = new StdClass();
  $file->uri = $file_uri;
  $file->focal_point = '30,50';

  return theme('responsive_image', array(
    'file' => $file,
    'style' => 'basic_' . $mode,
  ));
}

/**
 * Implements hook_responsive_default_styles().
 */
function responsive_image_styles_responsive_default_styles() {
  $styles = array(
    'basic_cropped' => array(
      'description' => 'Basic cropped responsive image style',
      'type' => 'min_scale',
      'cover' => TRUE,
      'ls' => array(
        'width' => 2560,
        'height' => 1440,
        'min_width' => 160,
        'steps' => 160,
        'interpolation' => 'quadric',
      ),
    ),
    'basic_adaptive' => array(
      'description' => 'Basic adaptive responsive image style',
      // Scale and crop.
      'type' => 'scale',
      'cover' => FALSE,
      'ls' => array(
        'interpolation' => 'cubic',
        'width' => 1200,
        'min_width' => 160,
      ),
    ),
  );

  return $styles;
}

/**
 * Get all styles from hook implementations and cache them.
 */
function &responsive_image_styles_get_base_styles() {
  static $cache = array();

  if (count($cache) != 0) {
    return $cache;
  }

  $cache = module_invoke_all('responsive_default_styles');
  drupal_alter('responsive_default_styles', $cache);

  foreach ($cache as $ndx => $item) {
    $cache[$ndx]['name'] = $ndx;
    $cache[$ndx]['available_ratios'] = array();
    foreach (array('ls', 'sq', 'po') as $ratio) {
      if (isset($cache[$ndx][$ratio])) {
        $val = isset($cache[$ndx][$ratio]['min_width']) ? $cache[$ndx][$ratio]['min_width'] : $cache[$ndx][$ratio]['min_height'];
        $max_val = isset($cache[$ndx][$ratio]['min_width']) ? $cache[$ndx][$ratio]['width'] : $cache[$ndx][$ratio]['height'];
        $step_width = isset($item['step_width']) ? $item['step_width'] : RESPONSIVE_IMAGE_STYLES_STEPS;
        $val += 2 * $step_width;
        $cache[$ndx][$ratio]['noscript'] = min($max_val, $val);
        $cache[$ndx]['available_ratios'][] = $ratio;

        // TODO: Fix interpolations other than linear, and when working enable
        // them again.
        // For now discard any interpolation-methods other than linear.
        // If (empty($cache[$ndx][$ratio]['interpolation'])) {.
        $cache[$ndx][$ratio]['interpolation'] = 'linear';
        // }.
      }
    }
  }
  return $cache;
}

/**
 * Add default styles.
 */
function _responsive_image_styles_default_add_style($type, $width, $height) {
  $min_scale_effect = variable_get('responsive_image_styles_scale_min', 'focal_point_scale_and_crop');

  if ($type == 'min_scale') {
    return array(
      'effects' => array(
        array(
          'name' => $min_scale_effect,
          'weight' => 0,
          'data' => array(
            'width' => $width,
            'height' => $height,
            'upscale' => FALSE,
          ),
        ),
      ),
    );
  }
  if ($type == 'min_scale_no_crop') {
    return array(
      'effects' => array(
        array(
          'name' => 'responsive_image_styles_scale_min',
          'weight' => 0,
          'data' => array(
            'width' => $width,
            'height' => $height,
            'upscale' => FALSE,
          ),
        ),
      ),
    );
  }
  if ($type == 'scale') {
    return array(
      'effects' => array(
        array(
          'name' => 'image_scale',
          'weight' => 0,
          'data' => array(
            'width' => $width,
            'height' => $height,
            'upscale' => FALSE,
          ),
        ),
      ),
    );
  }
}

/**
 * Compute width and height.
 */
function _responsive_image_styles_compute_width_and_height($size, &$width, &$height, $s, $key) {

  if (isset($size['width']) && isset($size['height'])) {

    $aspect = $size['width'] / $size['height'];

    if ($key == 'width') {
      $width = $s;
      $height = round($s / $aspect);
    }
    else {
      $height = $s;
      $width = round($s * $aspect);
    }
  }
  elseif ($key == 'width') {
    $width = $s;
    $height = NULL;
  }
  elseif ($key == 'width') {
    $height = $s;
    $width = NULL;
  }
}

/**
 * Get interpolation function.
 */
function _responsive_image_get_interpolation_fn($type) {
  if ($type == 'quadric') {
    $func = function ($input) {
      return $input * $input;
    };
  }
  elseif ($type == 'cubic') {
    $func = function ($input) {
      return $input * $input * $input;
    };
  }
  else {
    $func = function ($input) {
      return $input;
    };
  }
  return $func;
}

/**
 * Iterate through all ratios and steps and call $callback.
 *
 * @param callable $callback
 *   The function to call for every step.
 */
function responsive_image_styles_iterate_steps_and_call(callable $callback) {

  $base = responsive_image_styles_get_base_styles();

  foreach ($base as $key => $item) {
    foreach (array('ls', 'sq', 'po') as $ratio) {
      if (!isset($item[$ratio])) {
        continue;
      }
      $style_name = $key . '_' . $ratio . '_' . $item['type'] . '_';

      $sizes = $item[$ratio];
      $size_key = isset($sizes['min_width']) ? 'width' : 'height';
      $interpolate = _responsive_image_get_interpolation_fn($sizes['interpolation']);

      foreach (array(1.0, 2.0) as $scale) {

        $min = $scale * $sizes['min_' . $size_key];
        $max = $scale * $sizes[$size_key];

        $s = $min;

        $step_width = isset($item['step_width']) ? $item['step_width'] : RESPONSIVE_IMAGE_STYLES_STEPS;

        while ($s < $max) {

          $scalar = ($s - $min) / ($max - $min);
          $interpolated = $min + $interpolate($scalar) * ($max - $min);
          $interpolated = min($max, max($min, round($interpolated / 10.0) * 10));
          $callback($style_name, $ratio, $interpolated, $size_key, $item);
          $s += $scale * $step_width;
        }
        $callback($style_name, $ratio, $max, $size_key, $item);
      }
    }
  }
}

/**
 * Implements hook_image_default_styles().
 */
function responsive_image_styles_image_default_styles() {
  $return = array();

  $callback = function ($style_name, $ratio, $s, $size_key, $item) use (&$return) {
    $width = NULL;
    $height = NULL;
    _responsive_image_styles_compute_width_and_height($item[$ratio], $width, $height, $s, $size_key);

    $return[$style_name . $s] = _responsive_image_styles_default_add_style($item['type'], $width, $height);
  };

  responsive_image_styles_iterate_steps_and_call($callback);

  return $return;
}

/**
 * Get all used css class names.
 *
 * You can override all or partial class names via the
 * drupal variable 'responsive_images_css_class_names'.
 */
function responsive_images_get_css_class_names() {
  static $css_class_names = NULL;
  if (is_null($css_class_names)) {

    $default = array(
      'PROXY_SIZE_CONTAINER_SELECTOR' => FALSE,
      'SIMPLE_IMAGE_WRAPPER' => FALSE,
      'WRAPPER' => 'responsive-image-with-focal-point',
      'IMAGE' => 'responsive-image',
      'STATE' => array(
        'IS_LOADING' => 'responsive-image--loading-state',
        'IS_LOADED' => 'responsive-image--loaded-state',
        'IS_IN_VIEWPORT' => 'responsive-image--in-viewport-state',
        'IS_INITIAL_LOADING' => 'responsive-image--initial-loading-state',
        'ELEMENT_IS_HANDLED' => 'responsive-image--handled-state',
      ),
    );
    $css_class_names = drupal_array_merge_deep($default, variable_get('responsive_images_css_class_names', array()));

    drupal_alter('responsive_images_css_class_names', $css_class_names);
  }

  return $css_class_names;
}

/**
 * Helper to get style name.
 */
function _responsive_image_styles_get_style_name($style, $ratio, $size) {
  return $style['name'] . '_' . $ratio . '_' . $style['type'] . '_' . $size;
}

/**
 * Implements hook_field_formatter_info().
 *
 * Create the responsive image field formatter.
 */
function responsive_image_styles_field_formatter_info() {
  return array(
    'responsive_image_styles_image_formatter' => array(
      'label' => t('Responsive image'),
      'field types' => array('image', 'video_embed_field'),
      'settings'  => array(
        'preset' => 'basic_adaptive',
      ),
    ),
  );
}

/**
 * Field formatter options.
 */
function responsive_image_styles_as_options() {
  $data = responsive_image_styles_get_base_styles();
  $preset_options = array();
  foreach ($data as $item) {
    $preset_options[$item['name']] = $item['description'];
  }
  return $preset_options;
}

/**
 * Field formatter options form.
 */
function responsive_image_styles_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();
  $element['preset'] = array(
    '#type' => 'select',
    '#title' => t('Preset'),
    '#description' => t('Select the image preset'),
    '#default_value' => $settings['preset'],
    '#options'        => responsive_image_styles_as_options(),
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function responsive_image_styles_field_formatter_settings_summary($field, $instance, $view_mode) {

  $styles = responsive_image_styles_get_base_styles();

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('Use a responsive image with preset @preset (@machine_name)', array(
    '@machine_name'     => $settings['preset'],
    '@preset' => $styles[$settings['preset']]['description'],
  ));
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function responsive_image_styles_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $element = array();
  $settings = $display['settings'];
  $preset = $settings['preset'];

  foreach ($items as $item) {
    if ($field['type'] == 'video_embed_field') {
      $file = file_load_multiple(array(), array('uri' => $item['thumbnail_path']));
      $item = reset($file);
    }

    $element[] = array(
      '#theme' => 'responsive_image',
      '#style' => $preset,
      '#file' => $item,
    );
  }
  return $element;
}

/**
 * Implements hook_image_effects_info().
 */
function responsive_image_styles_image_effect_info() {
  $effects = array(
    'responsive_image_styles_scale_min' => array(
      'label' => t('Minimum resize'),
      'help' => t('Resizing an image so that width or height is equal or greater than the given values'),
      'effect callback' => 'responsive_image_styles_scale_min_effect',
      'dimensions callback' => 'responsive_image_styles_scale_min_dimensions',
      'form callback' => 'responsive_image_styles_scale_min_form',
      'summary theme' => 'responsive_image_styles_scale_min_summary',
    ),
  );

  return $effects;
}

/**
 * Implements scale_min_effect.
 */
function responsive_image_styles_scale_min_effect(&$image, $data) {

  $new_size = $image->info;
  responsive_image_styles_scale_min_dimensions($new_size, $data);

  if (!image_scale($image, $new_size['width'], $new_size['height'], FALSE)) {
    watchdog(
      'responsive_image_styles',
      'Image scale failed using the %toolkit toolkit on %path (%mimetype, %dimensions)',
      array(
        '%toolkit' => $image->toolkit,
        '%path' => $image->source,
        '%mimetype' => $image->info['mime_type'],
        '%dimensions' => $image->info['width'] . 'x' . $image->info['height'],
      ),
      WATCHDOG_ERROR);

    return FALSE;
  }
  return TRUE;
}

/**
 * Compute dimensions of min_scale-effect.
 */
function responsive_image_styles_scale_min_dimensions(array &$dimensions, array $data) {
  if ($dimensions['width'] && $dimensions['height']) {
    $scale_x = $data['width'] / $dimensions['width'];
    $scale_y = $data['width'] / $dimensions['height'];
    $scale = min(1.0, max($scale_x, $scale_y));

    $dimensions['width'] *= $scale;
    $dimensions['height'] *= $scale;

    $dimensions['width'] = round($dimensions['width']);
    $dimensions['height'] = round($dimensions['height']);

  }
}

/**
 * Get effect form.
 */
function responsive_image_styles_scale_min_form($data) {
  $form = image_resize_form($data);
  $form['width']['#required'] = TRUE;
  $form['height']['#required'] = TRUE;

  return $form;
}

/**
 * Method to calculate cropped image-size.
 */
function _responsive_image_styles_compute_crop($file, $style_name, $style_data, $focal_point) {

  if ($style_name == 'min_scale') {

    $crop_data = array(
      'width' => $style_data['width'],
      'height' => $style_data['height'],
    );

    $crop_data['x'] = focal_point_effect_calculate_anchor($file['width'], $crop_data['width'], $focal_point['x-offset']);
    $crop_data['y'] = focal_point_effect_calculate_anchor($file['height'], $crop_data['height'], $focal_point['y-offset']);
  }
  else {

    $crop_data = array(
      'width' => $file['width'],
      'height' => $file['height'],
      'x' => '0',
      'y' => '0',
    );
  }

  return $crop_data;
}

/**
 * Theme effect summary.
 */
function theme_responsive_image_styles_scale_min_summary($variables) {
  $data = $variables['data'];
  return theme('image_resize_summary', array('data' => $data));
}
