<?php
/**
 * @file
 * Main file for creating the responsive images.
 */

define('RESPONSIVE_IMAGE_STYLES_STEPS', 160);

/**
 * Implements hook_theme().
 */
function responsive_image_styles_theme() {
  return array(
    'responsive_image' => array(
      'variables' => array(
        'style' => NULL,
        'file' => array(),
        'attributes' => array(),
      ),
      'file' => 'responsive_image_styles.theme.inc',
    ),
  );
}

/**
 * Implements hook_page_build().
 *
 * Add css to the backend to fixing padding or margin on focalpoint images.
 */
function responsive_image_styles_page_build(&$page) {
  if (path_is_admin(current_path())) {
    ctools_add_css('responsive_image_styles_backend', 'responsive_image_styles');
  }
}

/**
 * Get all styles from hook implementations and cache them.
 */
function &responsive_image_styles_get_base_styles() {
  static $cache = array();

  if (count($cache) != 0) {
    return $cache;
  }

  $cache = module_invoke_all('responsive_default_styles');

  foreach ($cache as $ndx => $item) {
    $cache[$ndx]['name'] = $ndx;
    $cache[$ndx]['available_ratios'] = array();
    foreach (array('ls', 'sq', 'po') as $ratio) {
      if (isset($cache[$ndx][$ratio])) {
        $val = isset($cache[$ndx][$ratio]['min_width']) ? $cache[$ndx][$ratio]['min_width'] : $cache[$ndx][$ratio]['min_height'];
        $max_val = isset($cache[$ndx][$ratio]['min_width']) ? $cache[$ndx][$ratio]['width'] : $cache[$ndx][$ratio]['height'];
        $step_width = isset($item['step_width']) ? $item['step_width'] : RESPONSIVE_IMAGE_STYLES_STEPS;
        $val += 2 * $step_width;
        $cache[$ndx][$ratio]['noscript'] = min($max_val, $val);
        $cache[$ndx]['available_ratios'][] = $ratio;
      }
    }
  }

  return $cache;
}

/**
 * Add default styles.
 */
function _responsive_image_styles_default_add_style($type, $width, $height) {
  $min_scale_effect = variable_get('responsive_images_min_scale_effect', 'focal_point_scale_and_crop');

  if ($type == 'min_scale') {
    return array(
      'effects' => array(
        array(
          'name' => $min_scale_effect,
          'weight' => 0,
          'data' => array(
            'width' => $width,
            'height' => $height,
            'upscale' => FALSE,
          ),
        ),
      ),
    );
  }
  if ($type == 'scale') {
    return array(
      'effects' => array(
        array(
          'name' => 'image_scale',
          'weight' => 0,
          'data' => array(
            'width' => $width,
            'height' => $height,
            'upscale' => FALSE,
          ),
        ),
      ),
    );
  }
}

/**
 * Compute width and height.
 */
function _responsive_image_styles_compute_width_and_height($size, &$width, &$height, $s, $key) {

  if (isset($size['width']) && isset($size['height'])) {

    $aspect = $size['width'] / $size['height'];

    if ($key == 'width') {
      $width = $s;
      $height = round($s / $aspect);
    }
    else {
      $height = $s;
      $width = round($s * $aspect);
    }
  }
  elseif ($key == 'width') {
    $width = $s;
    $height = NULL;
  }
  elseif ($key == 'width') {
    $height = $s;
    $width = NULL;
  }
}

/**
 * Some default styles.
 */
function responsive_image_styles_image_default_styles() {
  $base = responsive_image_styles_get_base_styles();
  $return = array();

  foreach ($base as $key => $item) {
    foreach (array('ls', 'sq', 'po') as $ratio) {
      if (!isset($item[$ratio])) {
        continue;
      }
      $style_name = $key . '_' . $ratio . '_' . $item['type'] . '_';

      $sizes = $item[$ratio];
      $size_key = isset($sizes['min_width']) ? 'width' : 'height';

      foreach (array(1.0, 2.0) as $scale) {

        $min = $scale * $sizes['min_' . $size_key];
        $max = $scale * $sizes[$size_key];

        $s = $min;
        $width = NULL;
        $height = NULL;
        $step_width = isset($item['step_width']) ? $item['step_width'] : RESPONSIVE_IMAGE_STYLES_STEPS;

        while ($s < $max) {
          _responsive_image_styles_compute_width_and_height($sizes, $width, $height, $s, $size_key);

          $return[$style_name . $s] = _responsive_image_styles_default_add_style($item['type'], $width, $height);
          $s += $scale * $step_width;
        }
        _responsive_image_styles_compute_width_and_height($sizes, $width, $height, $s, $size_key);
        $return[$style_name . $max] = _responsive_image_styles_default_add_style($item['type'], $width, $height);
      }
    }
  }

  return $return;
}

/**
 * Get all used css class names.
 *
 * You can override all or partial class names via the
 * drupal variable 'responsive_images_css_class_names'.
 */
function responsive_images_get_css_class_names() {
  static $css_class_names = NULL;
  if (is_null($css_class_names)) {

    $default = array(
      'WRAPPER' => 'focal-point-wrapper',
      'IMAGE' => 'responsive-image',
      'STATE' => array(
        'IS_LOADING' => 'responsive-image--loading-state',
        'IS_LOADED' => 'responsive-image--loaded-state',
        'IS_IN_VIEWPORT' => 'responsive-image--in-viewport-state',
        'IS_INITIAL_LOADING' => 'responsive-image--initial-loading-state',
        'ELEMENT_IS_HANDLED' => 'responsive-image--handled-state'
      ),
    );
    $css_class_names = drupal_array_merge_deep($default, variable_get('responsive_images_css_class_names', array()));
  }

  return $css_class_names;
}


/**
 * Helper to get style name.
 */
function _responsive_image_styles_get_style_name($style, $ratio, $size) {
  return $style['name'] . '_' . $ratio . '_' . $style['type'] . '_' . $size;
}

/**
 * Implements hook_field_formatter_info().
 *
 * Create the responsive image field formatter.
 */
function responsive_image_styles_field_formatter_info() {
  return array(
    'responsive_image_styles_image_formatter' => array(
      'label' => t('Responsive image'),
      'field types' => array('image', 'video_embed_field'),
      'settings'  => array(
        'preset' => 'fullscreen',
      ),
    ),
  );
}

/**
 * Field formatter options.
 */
function responsive_image_styles_as_options() {
  $data = responsive_image_styles_get_base_styles();
  $preset_options = array();
  foreach ($data as $item) {
    $preset_options[$item['name']] = $item['description'];
  }
  return $preset_options;
}


/**
 * Field formatter options form.
 */
function responsive_image_styles_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();
  $element['preset'] = array(
    '#type' => 'select',
    '#title' => t('Preset'),
    '#description' => t('Select the image preset'),
    '#default_value' => $settings['preset'],
    '#options'        => responsive_image_styles_as_options(),
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function responsive_image_styles_field_formatter_settings_summary($field, $instance, $view_mode) {

  $styles = responsive_image_styles_get_base_styles();

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('Use a responsive image with preset @preset (@machine_name)', array(
    '@machine_name'     => $settings['preset'],
    '@preset' => $styles[$settings['preset']]['description']
  ));
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function responsive_image_styles_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  $element = array();
  $settings = $display['settings'];
  $preset = $settings['preset'];

  foreach ($items as $item) {
    if ($field['type'] == 'video_embed_field') {
      $file = file_load_multiple(array(), array('uri' => $item['thumbnail_path']));
      $item = reset($file);
    }

    $element[] = array(
      '#theme' => 'responsive_image',
      '#style' => $preset,
      '#file' => $item,
    );
  }
  return $element;
}
